name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.1'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - run: flutter pub get

      - name: Setup keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/ci-lab.jks
          cat > android/key.properties <<EOF
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=${{ github.workspace }}/android/app/ci-lab.jks
          EOF

      - run: flutter analyze
      - run: flutter test
      #      - run: flutter build appbundle --release
      - run: flutter build apk --release

      #      - uses: actions/upload-artifact@v4
      #        with:
      #          name: app-release-aab
      #          path: build/app/outputs/bundle/release/app-release.aab
      - name: Distribute to testers
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > /tmp/sa.json
          head -c 40 /tmp/sa.json
          npm install -g firebase-tools
          firebase appdistribution:distribute \
            build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --groups testers \
            --debug
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/sa.json